postgres:
  image: postgres:latest
  container_name: yazo-cms-adonis
  restart: always
  environment:
    - TZ=America/Sao_Paulo
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
  ports:
    - '5432:5432'
